#pragma once
extern CComponentTransformManager		GComponentTransformManager;
extern CComponentStaticMeshManager		GComponentStaticMeshManager;
extern CComponentLightManager			GComponentLightManager;
extern CComponentPhysicsManager			GComponentPhysicsManager;
extern CComponentCameraManager			GComponentCameraManager;
